-- ============================================================
-- 06_dim_investor.sql
-- Investor dimension.
-- 500 synthetic investors generated by clean_transactions.py.
-- Populated by scripts/etl/load_dimensions.py (Day 4).
--
-- All investor attributes are synthetically derived for
-- portfolio demonstration. Replace with real KYC data
-- if actual investor records become available.
-- ============================================================

CREATE TABLE IF NOT EXISTS dbo.Dim_Investor (
    investor_key        SERIAL          NOT NULL,
    investor_id         VARCHAR(20)     NOT NULL,   -- 'INV00001' … 'INV00500'
    age_group           VARCHAR(10),                -- '18-25', '26-35', '36-45', '46-55', '55+'
    city                VARCHAR(50),
    state               VARCHAR(50),
    risk_profile        VARCHAR(20),                -- 'Conservative', 'Moderate', 'Aggressive'
    investor_segment    VARCHAR(20),                -- 'Retail' (< 2L/yr), 'HNI' (> 10L), 'Institutional'
    kyc_status          BOOLEAN         NOT NULL DEFAULT TRUE,

    CONSTRAINT pk_dim_investor              PRIMARY KEY (investor_key),
    CONSTRAINT uq_dim_investor_id           UNIQUE (investor_id),
    CONSTRAINT chk_dim_investor_segment     CHECK (investor_segment IN ('Retail', 'HNI', 'Institutional')),
    CONSTRAINT chk_dim_investor_risk        CHECK (risk_profile     IN ('Conservative', 'Moderate', 'Aggressive'))
);

COMMENT ON TABLE dbo.Dim_Investor IS
    '500 synthetic investors. Schema ready for real KYC data; substitute via clean_transactions.py --input flag.';
